### ISSUE TITLE
No replication when SG is restarted

### ISSUE THREAD

**Issue by ashvindersingh** [couchbaselabs/sg-replicate#10]
Scenario: 
- Start SG-1, SG-2 and sg-replicate. Both SG's are using walrus db. 
- Create documents on SG-2, and ensure its gets replicated to SG-1. Check via Admin interface
-  Restart the SG-1, this should wipe all the previous docs. 
expectation: sg-replicate should restart the replication and the docs on SG-1 should have the same revision as SG-2. 
Observation: sg-replicate does not detect that sg-1 has lost the docs and does not start the replication.

**Comment by tleyden** [comment]
> Restart the SG-1, this should wipe all the previous docs

This is an invalid real-world scenario.  Please re-test with SG backed with a persistent store -- either Couchbase Server or Walrus which dumps its contents to a file.
