### ISSUE TITLE
No conflict resolution mechanism

### ISSUE THREAD

**Issue by ashvindersingh** [couchbaselabs/sg-replicate#13]
scenario:
- start sg-1, sg-2 and sg-replicate
- sg-replicate config: {
    "changes_feed_limit": 50,
    "continuous_retry_time_ms": 15000,
    "replications":{
        "db":{
            "source_url": "http://localhost:4984",
            "target_url": "http://localhost:5984",
            "source_db": "db",
            "target_db": "db",
            "lifecycle": "continuous"
        },
        "db":{
            "source_url": "http://localhost:5984",
            "target_url": "http://localhost:4984",
            "source_db": "db",
            "target_db": "db",
            "lifecycle": "continuous"
        }
    }
}
~   
- create document on sg-2 and ensure its gets replicated to sg-1
- update doc-1 on sg-1 by adding field, say "field": "aaa"
- update doc-1 on sg-2 by adding field, say "new": "bbb"
- sg-replicate stops replication at point. The doc-1 on both sg-1 and sg-2 is now different.

**Comment by tleyden** [comment]
> sg-replicate stops replication at point.

Can you post logs or clarify what you mean?

> The doc-1 on both sg-1 and sg-2 is now different.

Can you post the values of doc-1 on sg-1 and sg-2?

Also, are you using the SG admin port?  If not, can you re-test?

**Comment by jchris** [comment]
It looks like both the replications in your config snippet have the name `db`, maybe it is not running in both directions?

**Comment by jchris** [comment]
I think I was able to sync a conflict doc, although my testing was different. I shut down sg-replicate to make the conflicting edits, and then was able to continue to move them around. Here's my config:

```
{
    "changes_feed_limit": 50,
    "continuous_retry_time_ms": 15000,
    "replications":{
  	"db-local":{
  	    "source_url": "http://localhost:4985",
  	    "source_db": "retail",
  	    "target_db": "regional",
        "channels" : ["sale"],
  	    "lifecycle": "continuous"
  	},
    "db-local-reverse":{
        "source_url": "http://localhost:4985",
        "target_db": "retail",
        "source_db": "regional",
        "channels" : ["sale"],
        "lifecycle": "continuous"
    }
  }
}
```
