### ISSUE TITLE
Set to "continuous" but does "oneshot"

### ISSUE THREAD

**Issue by househippo** [couchbaselabs/sg-replicate#17]
Its looks like the sg-replicate is not running in background and only does a one time sync. I have it configured for  "lifecycle": "continous".

Could someone give me some input on keeping it continous.

Here is the confg.json

```
{
    "changes_feed_limit": 50,
    "continuous_retry_time_ms": 15000,
    "replications":{
        "db-local":{
            "target_url":"http://ip_target:4984",
            "source_url":"http://ip_source:4985",
            "source_db": "db",
            "target_db": "db",
            "channels" : ["*"],
            "lifecycle": "continous"
        }
    }
}
```

But I get this when I run#  go build & ./cli
This it the first line out put and last line output.

Start:
16:12:21.674151 SYNCTUBE: replciation lifecycle string: continous

End
16:12:22.191069 CLI: Successfully ran one shot replication:

**Comment by tleyden** [comment]
Looks like you misspelled "continuous".  Try this?

```
{
    "changes_feed_limit": 50,
    "continuous_retry_time_ms": 15000,
    "replications":{
        "db-local":{
            "target_url":"http://ip_target:4984",
            "source_url":"http://ip_source:4985",
            "source_db": "db",
            "target_db": "db",
            "channels" : ["*"],
            "lifecycle": "continuous"
        }
    }
}
```

**Comment by tleyden** [comment]
If that works, can you update the ticket title to "Validate lifecycle parameter"?

**Comment by househippo** [comment]
Whatttt spelling is for suckers  :-)  

I got it working without issue after change. 

Thank you,
Traun

**Comment by tleyden** [comment]
Cool!  I opened https://github.com/couchbaselabs/sg-replicate/issues/18 to validate the parameter
