### ISSUE TITLE
Priorities Replication via Array Order

### ISSUE THREAD

**Issue by househippo** [couchbaselabs/sg-replicate#19]
OLD
```
"replications":{
        "db-local":{
            "source_url": "http://localhost:4985",
            "source_db": "db",
            "target_db": "db-copy",
            "lifecycle": "oneshot"
        },
        "grocery-sync-local":{
           "name":
            "source_url": "http://localhost:4985",
            "target_url": "http://sync.couchbasecloud.com",
            "source_db": "grocery-sync",
            "target_db": "grocery-sync",
            "lifecycle": "continuous",
            "channels": ["lists", "items"]
        }
    }
```

NEW
```
"replications":[
        {
           "name":"db-local"
            "source_url": "http://localhost:4985",
            "source_db": "db",
            "target_db": "db-copy",
            "lifecycle": "continuous",
             "channels": ["important1Channel", "important2Channel"]
        },
       { 
           "name":"db-local-all"
            "source_url": "http://localhost:4985",
            "source_db": "db",
            "target_db": "db-copy",
            "lifecycle": "continuous",
             "channels": ["*"]
        }
    ],
"orderPriority":true
```
So in the above "NEW" method. Its performs db-local replication first & waits for completion , before going to the other dbs or channels when "orderPriority" set to true. The idea would be to make it so that different channels , in the same database, could be replicated by priority.  I'm not sure if currently each replication is set to its on GO routine or not.

**Comment by tleyden** [comment]
Have you tested yet to make sure it doesn't already behave that way?

**Comment by househippo** [comment]
Good Idea. Let me test and read the logs at target side SG. I know It does them asynchronously but not sure if they did them in order or not.

**Comment by househippo** [comment]
> Have you tested yet to make sure it doesn't already behave that way?

I tested it out with filtering by channels on the same SG database and "Works as Advertised".
