### ISSUE TITLE
sg-replicate not replicating _sync documents

### ISSUE THREAD

**Issue by ArihantRk** [couchbaselabs/sg-replicate#29]
sg-replicate is excluding _sync documents, reason might be _sync:seq will have conflicts as it is common in both syncgateway instances. but what is the significance of removing the "_sync:user" and "_sync:role" documents from replication.
 in this case, all user documents are not replicated.

below are the sequence of steps are done only for replication from sync1 to sync2
1. created user in sync1 and created session which are not replicated to sync2
2. inserted documents in sync1 and all documents are replicated to sync2 
In this case if i want to access the documents fro sync2 , i ned to create the same user in sync2 ,session and access it.
This will be helpful if used documents are not changing..

but what if the user deleted or removed access from docs which will not replicated to sync2.
From above setup, i can not switch to sync2 and access the documents incase of sync1 failed
can anyone explain what is the significance of excluding user documents replication.

**Comment by tleyden** [comment]
As @snej mentioned on the google group:

> Those aren’t documents (at the Couchbase Mobile level), just metadata that’s stored in the bucket.
