### ISSUE TITLE
Should user documents be sync'd?

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/sg-replicate#30]
Originally asked by @ArihantRk on the google group -- sg-replicate does not sync user documents.  

We should:

* Document the current behavior
* Come up with a long term plan in terms of whether this will be supported or not.

**Comment by ArihantRk** [comment]
What is the usecase if user documents not replicating to other syngateway. How can same user access the document from other syngateway instance.

**Comment by tleyden** [comment]
This isn't currently on our roadmap
