### ISSUE TITLE
One way replication from sg-2 to sg-1

### ISSUE THREAD

**Issue by ashvindersingh** [couchbaselabs/sg-replicate#9]
Setup:
- Launch SG-1 with walrus db
- Launch SG-2 with walrus db
- Launch sg-replicate with settings as
{
    "changes_feed_limit": 50,
    "continuous_retry_time_ms": 15000,
    "replications":{
        "db":{
            "source_url": "http://localhost:4984",
            "target_url": "http://localhost:5984",
            "source_db": "db",
            "target_db": "db",
            "lifecycle": "continuous"
        },
        "db":{
            "source_url": "http://localhost:5984",
            "target_url": "http://localhost:4984",
            "source_db": "db",
            "target_db": "db",
            "lifecycle": "continuous"
        }
    }
}
- Create and update documents on SG-1
expecting SG-2 to automatically get the docs from SG-1. 
observation: No docs received on SG-2. 

Further more, if create documents on SG-2, SG-1 gets the documents.

**Comment by tleyden** [comment]
@ashvindersingh is this using the Sync Gateway admin port as we discussed yesterday?  From the port numbers, it looks like the user port.

Also, please post configuration json surrounded by triple backticks and pretty-printed.  See the Syntax Highlighting section here: https://guides.github.com/features/mastering-markdown/ -- json pretty printing can be done on the command line with `jq` or online here: https://jsonformatter.curiousconcept.com/

**Comment by ashvindersingh** [comment]
Steps to reproduce this issue: 
- Please clone https://github.com/couchbaselabs/sync-gateway-tests
- Please follow the steps in the above repo to configure the repo
- Make two copies of the file /upgrade_tests/cbl_long_running_tests.js
- Please rename them test_1.js and test_2.js
- Edit the both files and change the 
sg.url = "http://127.0.0.1:4985"
var sgdb = 'http://127.0.0.1:4985/db/';

to point to the respective SG urls. 
- Make a copy of config/local.js and rename it to test_2_local.js
- Edit and change the LiteServPort to 59861
- Setup SG-replicate with config https://gist.github.com/ashvindersingh/49a9cfacb501c414ab3b
- Change the ipaddress as per your environment
- Setup two couchbase-server 3.1.x
- Configure your two sync gateways to point different couchbase server
- Sample sg config https://gist.github.com/ashvindersingh/d32f0be95bde994acb8e 
- launch scripts from a different consoles
- example : node test_1.js

Observation: 
SG-1: Some docs have missing rev-ids from SG-2
SG-2: ditto as above
SG-replicate: goes in an endless loop and does not come out of it.

**Comment by tleyden** [comment]
@ashvindersingh can you post the sg-replicate logs?

> SG-replicate: goes in an endless loop and does not come out of it.

With  continuous replication, it's supposed to go into an endless loop.  With the logs it might reveal more.

**Comment by ashvindersingh** [comment]
Please see ticket for logs: https://issues.couchbase.com/browse/CBL-39

**Comment by jchris** [comment]
Are you able to reproduce with walrus instead of CBS? Can you paste the test output or link to the test / assertion that's failing? That might help us get deeper into the issue.

**Comment by ashvindersingh** [comment]
Walrus wasn't recommend so these tests were run against the CBS-3.1.0. I have attached the log output in the jira ticket

**Comment by jchris** [comment]
I looked through sg-replicate.txt but it looks like the STDOUT from SG replicate. If I know which tests are failing or which assertions, then I can start to figure out the code path. If you don't have an easy way to run it again under this environment that's fine. If we had all the output we might even be able to spot the bug just by thinking through the code.

**Comment by tleyden** [comment]
I think this was a bug in the test.  This is covered in the [sg-replicate functional test suite](https://github.com/couchbaselabs/mobile-testkit/blob/master/testsuites/syncgateway/functional/test_sg_replicate.py)
